[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"


[lib]
name = "guessing_game"
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.0"

[dependencies.pyo3]
version = "0.24.0"
features = ["abi3-py38"]
